### ISSUE TITLE
Operaciones básicas 

### ISSUE THREAD

**Issue by isaireyesp1** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-isaireyesp1#1]
[Ejercicios Operaciones Basicas ISAI 1AS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-isaireyesp1/files/7174935/Ejercicios.Operaciones.Basicas.ISAI.1AS.pdf)

**Comment by Arlet04** [comment]
Portada (excelente) contiene todos los datos requeridos 25 puntos
Procedimiento (notable) contiene suficientes ejemplos pero no basta ya que faltó explicar el procedimiento de cada uno de ellos 22 puntos
Figuras, ilustraciones y fotografías (excelente) muestra suficientes fotografías 25 puntos
Resultados y conclusiones (excelente) cumple con las condiciones establecidas 25 puntos
Total: 97/100
calificación: 19.4% / 20%
calificado por: Jeanette Arlet Salazar Nicolás

**Comment by josealfredo79** [comment]
Bien hecho y revisado
